### ISSUE TITLE
[E2E module to LLM]

### ISSUE THREAD

**Issue by Lewis-Lu** [hustvl/Senna#10]
Hi there,

Thanks for releasing the repo.

Could you please identify how we convey the features from E2E_{perception, prediction} modules, like 3D info, trajectorys to the token embeddings ? As of today, I have not found the clue that the VLM module senna_llava_llama.py integrates this part into.

Best,
Lewis

**Comment by PG-Wang** [comment]
Sorry to disturb you, I have not found the module about senna_E2E and I don't find out how to realize the interaction code between senna_VLM module and VAD-like E2E code, have you figured out?

**Comment by rb93dett** [comment]
> Hi there,
> 
> Thanks for releasing the repo.
> 
> Could you please identify how we convey the features from E2E_{perception, prediction} modules, like 3D info, trajectorys to the token embeddings ? As of today, I have not found the clue that the VLM module senna_llava_llama.py integrates this part into.
> 
> Best, Lewis

Hi, Lewis,

When ground-truth perception results are unavailable, Senna can convert the 3D info and trajectories output by the E2E module into prompts required for scene understanding, such as Motion Intention Prediction. However, this is not the main focus of this paper, so we did not discuss it in detail. Nonetheless, thank you for your question, and we will explain this part more clearly in future updates to the paper.

**Comment by rb93dett** [comment]
> Sorry to disturb you, I have not found the module about senna_E2E and I don't find out how to realize the interaction code between senna_VLM module and VAD-like E2E code, have you figured out?

Since part of the Senna-E2E code is implemented based on the company's internal framework, it may not be fully open-sourced. However, I will try to open-source the core components of Senna-E2E in the future. To answer your question, as Senna-VLM outputs formatted meta-actions, Senna has a one-to-one embedding (randomly initialized) for each meta-action, which serves as the meta-action feature and is fed into Senna-E2E as an input feature for the planning module. During the training process of the Senna-E2E module, the weights of the meta-action embeddings are updated. You can also refer to the last few paragraphs of Sec III.B in the paper for more details.

**Comment by PG-Wang** [comment]
Thanks for your reply!

**Comment by Lewis-Lu** [comment]
@rb93dett  Thanks a lot for the reply. Closing this issue.
